---
title: "EC Partitioning"
---

## A story of Partitioning

The CO~2~ analyzer is measuring CO~2~ flux or what we called net ecosystem exchange (F~CO2~ or NEE), it's essentially a difference between ecosystem respiration (Reco) and gross primary production (GPP), as $NEE = Reco - GPP$. Partitioning is to partition the NEE measured by tower into GPP and Reco, which is important in flux data analysis [(Burba, 2022)](https://www.licor.com/env/products/eddy-covariance/ec-book/).

There are mainly two groups of NEE partitioning: one group methods are empirical models (establish site specifics relationship between nighttime flux and biophysical controls, then used the relationship to approximate daytime Reco). Another group of methods is more complex but less empirical models (light response curves using just daytime or 24-hour data) [(Burba, 2022)](https://www.licor.com/env/products/eddy-covariance/ec-book/).

Random thoughts: When talk about partitioning and check into these papers, researchers are trying hard on identifying the best way for partitioning and estimating GPP and Reco accurately. My random thought is: why partitioning? why not designing sensors on measuring GPP?

CO2 analyzers are designed due to eddies, understandable. Reco can't be measured, which require no sunlight for the ecosystem, understandable. But, anyways for measuring GPP directly? ........

<https://www.bgc-jena.mpg.de/5624848/Flux-partitioning>

## Partitioning with REddyProc

(Wutzler et al., 2018) Read from 2024/10/31 to , check the paper here: https://doi.org/10.5194/bg-15-5015-2018

### Summary

## Estimation of global LAI and FAPAR using radiative transfer models (Myneni et al., 1997)

Read from 2024/10/30 to , check the paper here: 10.1109/36.649788

## On the temperature dependence of soil respiration (Lloyd & Taylor, 1994) - Nighttime Partitioning

From 2024/11/01 to , check the [paper](https://www.jstor.org/stable/2389824)

Research Qs:

-   Rx​ reflects the **baseline respiration rate** that is influenced by ecosystem factors like MMM.

-   f(T) captures the **temperature sensitivity** in a generalized form that applies across datasets.

1884 Van't Hoff derivative of the natural logarithm of the reaction rate constant (lnk) with respect to temperature (T). Van’t Hoff observed that the rate of chemical reactions changes exponentially with temperature. And the derivative of it in linear relationship. $$\frac{d(\ln k)}{dT} = \frac{E}{\mathcal{R}T^2} + c$$

1889 Arrhenius built on van’t Hoff’s observations and incorporated the concept of energy distribution among reacting molecules (based on Boltzmann's statistical mechanics). He simplified van’t Hoff’s equation by assuming c=0 and **integrating** it into a simpler form to explain reaction kinetics.

$$k = d e^{-\frac{E}{\mathcal{R}T}}$$

Where d is a constant, E is activation energy, T is the absolute temperature (K). But we would like to involve a reference temperature (283.15K), where standardize the temperature dependencies (enables consistent comparisons across data sets, standardizing variation between ecosystems).

$$R = R_{10} e^{\frac{E}{\mathcal{R} \cdot 283.15} \left(1 - \frac{283.15}{T}\right)}$$

Soil respiration involves changing populations of many different organisms, each undergoing a complex series of reactions, which is likely that the activation energies may indeed increase with decreasing temperature. Kavanau (1951) utilized kinetic theory to derive a semi-empirical formulation that effectively gives a decrease in activation energy with increasing temperature.

$$k_R = P \left[1 - e^{-\frac{E_0}{T - T_0}}\right]$$

A simplified version:

$$
R = A e^{-\frac{E_0}{T - T_0}}
$$

Final form relative to 10 celsius degree by Lloyd & Taylor, 1994:

$$R_{\text{eco}}(T) = R_{\text{eco,ref}} e^{E_0 \left( \frac{1}{T_{\text{Ref}} - T_0} - \frac{1}{T - T_0} \right)}$$

This equation indeed used to calculate Reco at night for nighttime partitioning method.

1898 Q10: [Van't Hoff in 1898](https://archive.org/details/lecturesontheore0000drjh/page/226/mode/2up) (p226-228) observed from the data he collected for T (temperature) vs k (reaction rate constant), for many chemical reactions, the k typically increases by a factor of 2 to 3 for every 10°C increase in temperature \[T VS. Reaction Rates\]. This is in exponential relationship. To further test if reaction rates are in certain times for 10°C intervals, we used: $log_{10}k = a +bt$ & $(k_{t+10})/k_t = 10^{10b}$

This make us available to calculate any ratios, such as for ethyl acetate: 9.4°C k=2.307 & 44.94°C k=21.648, sub to $log_{10}k = a +bt$, we are able to calculate b and then $10^{10b}$ to get the ratios.

The idea posted by Van't Hoff was further widely used in ecology study.

## On the seperation of net ecosystem exchange into assimilation and ecosystem respiration: review and improved algorithm (Reichstein, 2005)

From 2024/11/24 to , check the paper [here](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2486.2005.001002.x): doi: 10.1111/j.1365-2486.2005.001002.x

Main Research Question: analyse the effect of short-term vs. long-term temperature sensitivity on the estimation of daytime Reco and GPP.

-   (The observed seasonal temperature sensitivity of ecosystem respiration includes influences from other factors (e.g., soil moisture, growth) that vary with temperature, making it different from the actual short-term temperature sensitivity.)

Improved Algorithm:

-   Collect half-hourly eddy covariance flux data, ensuring high-quality night-time data through a turbulence filtering threshold.

-   Segment the data into 15-day windows, with a 10-day overlap between consecutive windows.

-   Perform short-term regressions within each window to estimate temperature sensitivity (E0).

-   Linearly interpolate Rref based on estimates from 4-day periods and integrate E0, short into respiration calculations.

-   Use the improved algorithm to partition NEE into GEP and Reco while addressing biases from long-term temperature sensitivity.

The paper for REddyProc package: <https://bg.copernicus.org/articles/15/5015/2018/>

Daytime flux partitioning method -\> Lasslop et al. (2010)

Light–response curves are fit to daytime NEE measurements and respiration is estimated from the intercept of the ordinate, which avoids the use of potentially problematic nighttime data.

Falge et al. (2001)

Biases of nighttime partitioning methods:

Lasslop et al. (2010)

Methods that rely on nighttime data for partitioning may be biased due to the frequent nighttime suppression of turbulence and dominance of advective fluxes not measured by conventional EC systems (Goulden et al., 1996; Aubinet et al., 2000; Feigenwinter et al., 2004; Aubinet, 2008).

Daytime data-based estimate including temperature sensitivity of respiration.

[(Michaelis and Menten, 1913](https://www.chem.uwec.edu/Chem352_F18/pages/readings/media/Michaelis_&_Menton_1913.pdf)) examines the concentration of sucrose affects the rate of its enzymatic inversion, models how reaction velocity (rate of product formation) depends on the substrate concentration. Which expresses reaction rate as a hyperbolic function:

$$v = \frac{V_{\text{max}}[S]}{K_m + [S]}$$

where $V_{max}$​ is the maximum rate, \[S\] is the substrate concentration, and $K_m$​ is the Michaelis constant (substrate concentration at half-maximum rate).

Rectangular hyperbolic light-response curve (Falge et al., 2001)

$$\begin{equation}\mathrm{NEE} = \frac{\alpha \beta R_g}{\alpha R_g + \beta} + \gamma\end{equation}$$

$\alpha \, (\mu\text{mol C J}^{-1})$ is the canopy light utilization efficiency and represents the initial slope of the light–response curve

$\beta \, (\mu\text{mol C m}^{-2} \text{s}^{-1})$ is the maximum CO2 uptake rate of the canopy at light saturation

$\gamma \, (\mu\text{mol C m}^{-2} \text{s}^{-1})$ is the ecosystem respiration

$R_g \, ({W m}^{-2})$ is the global radiation
