---
title: "Terminology"
---

## C Related

## Plants Related

-   Leaf area index (LAI): one-sided green leaf area per unit ground area

-   Fraction of absorbed photosynthetic active radiation (FAPAR): fraction of photosynthetic active radiation (0.4–0.7um) absorbed by the vegetation

## Remote Sensing

-   [Normalized Difference Vegetation Index (NDVI)](https://hakimabdi.com/blog/birth-of-the-normalized-difference-vegetation-index-and-the-paradigm-shift-in-satellite-remote-sensing-of-the-environment) first introduced by Rousie and his colleagues in “[*Monitoring Vegetation Systems in the Great Plains with ERTS*](https://ntrs.nasa.gov/api/citations/19740022614/downloads/19740022614.pdf)”, defined as $$NDVI = (NIR-RED)/(NIR+RED) = [\rho(0.86\mu m)-\rho(0.66\mu m)] / [\rho(0.86\mu m)+\rho(0.66\mu m)]$$, where $\rho$ represents the radiance in reflectance units. Vegetation reflects a high amount of NIR (40-60%), absorbs RED (thus reflect less, below 10%) due to chlorophyll. Thus, healthy vegetation has higher NDVI due to high NIR-to-red ratio. Normalization is essential in NDVI to minimize the effects of lighting conditions, sun angle, and atmospheric interference, making vegetation measurements more consistent and comparable across different times and locations. Consider what will happen during a cloudy day vs. sunny day?
-   Normalized Difference Water Index (NDWI) introduced by [Gao](https://www.sciencedirect.com/science/article/pii/S0034425796000673) in 1996, defined as $$NDWI = (NIR-SWIR)/(NIR+SWIR) = [\rho(0.86\mu m)-\rho(1.24\mu m)] / [\rho(0.86\mu m)+\rho(1.24\mu m)]$$. Absorption by vegetation liquid water near $0.86\mu m$ is negligible and weak liquid absorption at $1.24\mu m$.
